### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by char-46** [iTXTech/mcl-addon#2]
## 版本
mirai-console 2.10.1
mirai-console-terminal 2.10.1

soyuz 1.0.0

MCL 2.0.0-beta.3-a566665

## 日志

> `2022-04-20 18:25:34 E/MCL Addon: java.lang.NoSuchMethodError: 'net.mamoe.mirai.console.MiraiConsoleImplementation net.mamoe.mirai.console.MiraiConsoleImplementation.getOrigin()'
java.lang.NoSuchMethodError: 'net.mamoe.mirai.console.MiraiConsoleImplementation net.mamoe.mirai.console.MiraiConsoleImplementation.getOrigin()'
        at org.itxtech.soyuz.handler.builtin.PushLogHandler.<init>(PushLogHandler.kt:58)
        at org.itxtech.soyuz.handler.HandlerManager.<clinit>(handler.kt:44)
        at org.itxtech.mcl.addon.Addon.<init>(Addon.kt:51)
        at org.itxtech.mcl.addon.PluginMain.onEnable(PluginMain.kt:47)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:117)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:164)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:36)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:47)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:135)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:177)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:202)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:401)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:156)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:155)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:145)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:184)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:184)
        at org.itxtech.mcl.Loader.main(Loader.java:79)`

**Comment by PeratX** [comment]
Soyuz需要Mirai 2.11才可使用
